[package]
name = "contracts"
edition = { workspace = true }
rust-version = "1.81"

[lib]
path = "metadata.rs"

[dependencies]
sdk = { workspace = true }
contract1 = { workspace = true, features = ["sp1"] }
sp1-sdk = "=5.0.3"

[build-dependencies]
sp1-helper = "=5.0.0"

[features]
build = []
